version: '3'

services:
    php:
        image: akeneo/php:7.2
        environment:
            COMPOSER_HOME: /home/docker/.composer
            PHP_IDE_CONFIG: 'serverName=docker'
            PHP_XDEBUG_ENABLED: "${PHP_XDEBUG_ENABLED}"
            PHP_XDEBUG_IDE_KEY: XDEBUG_IDE_KEY
            XDEBUG_CONFIG: 'remote_host=${DOCKER_HOST_IP}'
        user: docker
        volumes:
            - ./:/home/docker/
            - ~/.composer:/home/docker/.composer
        working_dir: /home/docker/

networks:
    training:
